--Cuantos vehiculos ingreso cada operario
SELECT
COUNT(IT.GUID_USUARIO_CREA) AS	[NUMERO DE VEHICULOS INGRESADOS]
,IT.GUID_USUARIO_CREA		AS	[GUID_USUARIO]
,U.NOMBRE					AS	[PERSONA QUE INGRESA EL VEHICULO]
FROM ITEM_FACTURABLE IT
INNER JOIN USUARIO u ON IT.GUID_USUARIO_CREA = U.GUID
GROUP BY IT.GUID_USUARIO_CREA,U.NOMBRE

-- Cuantos regreso al cliente
SELECT
COUNT(IT.GUID_USUARIO_CREA)		AS	[VEHICULOS DEVUELTOS]
,IT.GUID_USUARIO_CREA			AS	[GUID_USUARIO]
,U.NOMBRE						AS	[PERSONA QUE DEVUELVE EL VEHICULO]	
FROM ITEM_FACTURABLE IT
INNER JOIN USUARIO U ON IT.GUID_USUARIO_CREA = U.NOMBRE	
INNER JOIN ESTADO_NEGOCIO EN ON IT.GUID_ESTADO_INGRESO = EN.GUID
WHERE EN.VALOR = 'Devuelto'
GROUP BY IT.GUID_USUARIO_CREA,U.NOMBRE	

--Detallado de las transacciones con valor cobrado

SELECT * FROM ITEM_FACTURABLE IT 
WHERE FECHA_DEVOLUCION IS NOT NULL
AND TOTAL_TARIFA IS NOT NULL

--Inventario de los vehiculos valet en el parqueadero

SELECT * FROM ITEM_FACTURABLE IT
INNER JOIN VEHICULO V ON IT.GUID_VEHICULO = V.GUID
INNER JOIN ESTADO_NEGOCIO EN ON IT.GUID_ESTADO_INGRESO = EN.GUID
WHERE EN.VALOR = 'En sitio'