USE [master]
GO

/****** Object:  Database [City_Proyectos]    Script Date: 21/03/2021 1:01:42 p. m. ******/
CREATE DATABASE [City_Proyectos]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'City_Proyectos', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLDEVLOCAL\MSSQL\DATA\City_Proyectos.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'City_Proyectos_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLDEVLOCAL\MSSQL\DATA\City_Proyectos_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [City_Proyectos].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [City_Proyectos] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [City_Proyectos] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [City_Proyectos] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [City_Proyectos] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [City_Proyectos] SET ARITHABORT OFF 
GO

ALTER DATABASE [City_Proyectos] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [City_Proyectos] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [City_Proyectos] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [City_Proyectos] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [City_Proyectos] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [City_Proyectos] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [City_Proyectos] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [City_Proyectos] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [City_Proyectos] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [City_Proyectos] SET  DISABLE_BROKER 
GO

ALTER DATABASE [City_Proyectos] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [City_Proyectos] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [City_Proyectos] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [City_Proyectos] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [City_Proyectos] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [City_Proyectos] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [City_Proyectos] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [City_Proyectos] SET RECOVERY FULL 
GO

ALTER DATABASE [City_Proyectos] SET  MULTI_USER 
GO

ALTER DATABASE [City_Proyectos] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [City_Proyectos] SET DB_CHAINING OFF 
GO

ALTER DATABASE [City_Proyectos] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [City_Proyectos] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [City_Proyectos] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [City_Proyectos] SET QUERY_STORE = OFF
GO

ALTER DATABASE [City_Proyectos] SET  READ_WRITE 
GO

